name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
      - name: Write CML report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Correct environment variable
        run: |
          # Create a report file with model metrics
          {
            echo "# Model Performance Report"
            echo "## Metrics"
            cat metrics.txt
          } > report.md

          # Append visualizations to the report
          {
            echo "## Data Visualization"
            echo "![Feature Importance](feature_importance.png)"
            echo "![Residuals](residuals.png)"
          } >> report.md

          # Post the report as a comment in the PR
          cml comment create report.md


          
          
          
